### ISSUE TITLE
CLOSING (uncooperative) forever

### ISSUE THREAD

**Issue by robtex** [ACINQ/eclair-mobile#20] opened 2018-04-06 09:15 UTC
Set up a channel from eclair to my lnd node
For unknown reason eclair decided to uncooperatively close it shortly after (about 90 minutes or so).
Never actually used that or any other channel.
the channel has now been stuck in acinq as closing for days. Restarted app, phone and even cleared cache on it.
The closing TX is well confirmed
My three other channels are in state normal
https://www.robtex.com/lightning/channel/568042891378425856

**Comment by j3bm3ch** [comment] 2018-04-06 14:02
Same here. 
Set up an eclair channel to my lnd node yesterday with 150k satoshis in it. 
Channel gets confirmed and switches to normal state.
Push 20k sats through it to an invoice my node generated. Worked like a charm.
Tried to send a 1 sat transaction through it, was stopped by the cap rule. 
Deactivated fee capping, tried again with 10 sats.
Transaction goes into pending state and never gets confirmed.
Closed channel after a while, left force close checkbox unchecked.
Channel goes into uncooperative CLOSING state.
Pending transactions fails after a while.
Channel stays in CLOSING until now. 144 blocks have not been mined since then, so I check tonight again.

**Comment by pm47** [comment] 2018-04-06 21:15
@robtex to be sure, you have restarted the app after the tx having reached 144+ confirmations?

are you using any specific configuration in lnd to require higher delays?

**Comment by ken2812221** [comment] 2018-04-07 06:10
I use eclair wallet testnet and auto connect to your             
node, and I close the channel uncooperatively, now it is over 2500 confirmed. Does not refund to my wallet. txid: 80a9b539f4879ca39bea53b38b65c93052a84204b502eeeae57167d5a4e734cb
![](https://i.imgur.com/k3FD0zw.png)

**Comment by robtex** [comment] 2018-04-07 10:57
@pm47 default settings in lnd, on latest master.
closing transaction a67136696f3886e7a568ebe07af95461583e5fb76d44db23d041a85f57eac32b currently has 404 confirmations
have restarted the app, the phone, even cleared the cache.
lnd node has also been restarted
the three other sessions are still normal, might be only clightning nodes
not found in listchannels nor pendingchannels on the lnd node

**Comment by pm47** [comment] 2018-04-08 19:44
This is a duplicate of #17, please see updates there.

**Closed as completed by pm47** 2018-04-08 19:44 UTC
Labels: duplicate
