### ISSUE TITLE
Direct channel: Route not found.

### ISSUE THREAD

**Issue by kilrau** [ACINQ/eclair-mobile#207] opened 2019-07-25 12:24 UTC
![signal-attachment](https://user-images.githubusercontent.com/19181985/61873945-6663b680-aee7-11e9-9fa4-3bf7ab4d844c.jpeg)
![signal-attachment02](https://user-images.githubusercontent.com/19181985/61874080-cfe3c500-aee7-11e9-99b2-065e2e6eee0e.jpeg)

with a direct channel and enough outbound capacity to the other side: https://pastebin.com/rD0EtzZb

Hint: there might be lnd on the other side

**Comment by araspitzu** [comment] 2019-07-25 13:11
Hi @kilrau can you make sure the channel is in state NORMAL when attempting to send the payment? I don't see anything wrong in your setup, if after ensuring the channel is in NORMAL (when sending the payment) you still can't pay the remote, could you please enable logging (Options > Settings > Logging) and attach here the logs of eclair while you attempt the payment?

**Comment by kilrau** [comment] 2019-07-25 13:38
Channel is/was in state normal. EDIT: It's BTCPayServer on the other side, I suspect it's c-lightning.

Tried again, failed again, here the logs (just replaced the payment description by X, didn't touch anything else). It doesn't even show the payment failure which is very weird:
[eclair-wallet.log](https://github.com/ACINQ/eclair-mobile/files/3431802/eclair-wallet.log)

**Comment by araspitzu** [comment] 2019-07-25 14:06
Are you sure you haven't cut from the logs other important parts too? I can't find what happens when we query the network graph for a route to the recipient.

**Comment by kilrau** [comment] 2019-07-25 14:15
..

Here again an untouched version, copied via USB: 
[eclair-wallet.log](https://github.com/ACINQ/eclair-mobile/files/3431948/eclair-wallet.log)

**Comment by kilrau** [comment] 2019-07-25 14:17
Also, you can try opening a channel to the node (see channel data above) and sending a small payment yourself.

**Comment by araspitzu** [comment] 2019-07-25 15:07
Here are a few takes from an initial analysis: the invoice you're trying to pay contains route hints but eclair should ignore them and prefer the direct channel, (i'm saying should because i don't see the router response in the logs). In the case eclair is trying to use the route hints you might end up paying quite a bit in fees (they are proportional to the payment amount) and that can result in a failure if the selected channel has low capacity. Unfortunately to dig more into this i have to reproduce it locally so i'm going to open a channel to the recipient and try to do exactly the same payment.
NB: your direct channel is now being closed by the remote.

**Comment by kilrau** [comment] 2019-07-25 15:09
> NB: your direct channel is now being closed by the remote.

Yes, noticed that!

**Comment by araspitzu** [comment] 2019-07-26 12:54
Confirmed: there is an edge case where sending a large payment (close to `htlcMaximumMsat`) through a direct channel causes the path finding to wrongly evaluate the channel cost. Thanks for the report!

**Comment by araspitzu** [comment] 2019-08-02 08:02
Hi @kilrau the [latest version](https://github.com/ACINQ/eclair-mobile/releases/tag/v0.4.8-MAINNET) of eclair-mobile contains a fix for this issue, can you please check if you are able to send the payment?

**Closed as completed** 2019-08-09 11:00 UTC
Labels: bug

**Comment by kilrau** [comment] 2019-08-16 08:41
Sorry for only coming back to this now. Tested - fixed! Great stuff!
