### ISSUE TITLE
Incorrect balance displayed

### ISSUE THREAD

**Issue by ROBKEN2014** [ACINQ/eclair-mobile#22] opened 2018-04-06 20:40 UTC
Help me please. Receive 100k satoshi 2 times. APP only display 1 time. See the image in this link https://ibb.co/dKDsCH

**Comment by mautematico** [comment] 2018-04-06 23:01
As you don't have oppened LN channels yet, you could backup and restore your wallet.

To do so, first extract your recovery seed (24 words afaik), then delete + reinstall eclair.
Be ultra careful while extracting your recovery seed, if you fail to write it down correctly, your 200ksat will be lost forever.

Don't do it if you have opened channels, as recovery seed does not cover them.

**Comment by ROBKEN2014** [comment] 2018-04-07 16:16
I deposited another 210k satoshi, and still the wallet showed incorrect balance, still lacking 100k, even doing the bakup and restoring the wallet, still did not clear the balance, proving to be an interface problem. (transactions are shown, adding 410k satoshi, but the balance is added wrong!)

**Comment by AlbertPhan** [comment] 2018-04-07 19:29
I also have this exact problem. I sent 1mBTC in two seperate transations and they appear in the transaction history like OPs but the balance is wrong. I believe I tried to set up a payment channel before with 1mBTC but not sure if it went through because there is no history of it. I also reinstalled and the same problem exists.

**Comment by mautematico** [comment] 2018-04-08 23:31
@AlbertPhan, @ROBKEN2014, please extract your seed and try it on latest Electrum version.
It needs to be imported as BIP39 + BIP49 seed.

Electrum will display _correct_ balance. This means:
If electrum shows exact balance as expected **and there is no balance on LN channels,** then you can safely  reinstall eclair app, and everything should be there.

**But** if electrum displays fewer balance than expected, even if eclair does not report any balance on LN channels, then it means **there is** balance in LN channels, either in open, pending close or pending open state; in this  case please **do not delete app and do not delete app data**. Instead, provide additional details to help developer team identifying the bug.

**Comment by AlbertPhan** [comment] 2018-04-16 01:13
Balance shows correctly in Electrum. 
I already reinstalled the eclair wallet 0.3.1 but it still displays only 1 mBTC when it should be 2. I still have the old eclair wallet as well.

**Comment by sstone** [comment] 2018-05-25 09:34
Closed because it is a duplicate of #68, please follow progress there instead

**Closed as completed by sstone** 2018-05-25 09:34 UTC
