### ISSUE TITLE
Noob, looking for help. Channel was force closed for 'uncooperative'

### ISSUE THREAD

**Issue by dognip** [ACINQ/eclair-mobile#23] opened 2018-04-06 21:06 UTC
Hi,

I'm looking for some help. If this is the wrong location for that, please direct me to another location.

I opened a channel: https://api.blockcypher.com/v1/btc/main/txs/23abf0ca667072fe64b1067501bdd6bad78a8f3b1661d00a02c4fe4074e21748

It was then closed and deemed 'uncooperative'. My funds are locked up now? Is this for a specific amount of time? Do I need to do anything to retrieve them?

Thanks!

**Comment by sstone** [comment] 2018-04-06 23:03
This is a very common question, I've added it to our [FAQ](https://github.com/ACINQ/eclair-wallet/wiki/FAQ). You can get support for eclair and eclair-wallet on our [gitter](https://gitter.im/ACINQ/eclair).

Thanks!

**Comment by sstone** [comment] 2018-04-06 23:06
I forgot to add: in your case you should get your funds back in about 18 hours

**Comment by dognip** [comment] 2018-04-08 12:21
This has been written about in other issues but I see no solutions posted.. It has been well over 18 hours and my funds are still missing. Can anyone help?

**Comment by pm47** [comment] 2018-04-08 20:17
This is a duplicate of #17, please see updates there.

**Closed as completed by pm47** 2018-04-08 20:17 UTC
Labels: duplicate
