### ISSUE TITLE
Force close channel now stuck in CLOSING state after 1 day

### ISSUE THREAD

**Issue by n4spd** [ACINQ/eclair-mobile#80] opened 2018-05-28 01:09 UTC
I opened channel then 20 minutes later, I force closed it.
It's been over 1 day and status is stuck on CLOSING

channel id
e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb

funding tx
fa3197d9dcb1d76851475067993b696ec8166176fd1efa868ca1c026463b03e3

using Eclair 0.2-beta3

the follow log entries have the channel id in them:

2018-05-26 11:23:32,938 INFO  fr.acinq.eclair.io.Peer akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432  - channel id switch: previousId=8a037b905ddfaf3bd83dc53e93f0abc8246b888cc950f26a528d695a1bfe77ed nextId=e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb
2018-05-26 11:23:33,126 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$b e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - publishing funding tx for channelId=e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb fundingTxid=fa3197d9dcb1d76851475067993b696ec8166176fd1efa868ca1c026463b03e3
2018-05-26 11:23:33,177 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$b e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - committing txid=fa3197d9dcb1d76851475067993b696ec8166176fd1efa868ca1c026463b03e3
2018-05-26 11:23:33,246 INFO  fr.acinq.eclair.gui.Handlers   - successfully opened channel created channel e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb

2018-05-26 11:25:16,938 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a 0000000000000000000000000000000000000000000000000000000000000000 - restoring channel channelId=e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb

2018-05-26 11:41:11,636 WARN  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - force-closing channel at user request
2018-05-26 11:41:11,737 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - tx generation success: desc=main-delayed-output txid=6a04077bc3027e16319ef324521652789a4523e4c27d471ac9cb181c12e11285 amount=129148 tx=02000000000101d681c7ffba961f8ac8e49e48e409eccf7596f72b492430decccf9081ed940e3e000000000090000000017cf801000000000017a9140c268e1cfd549df4c269958fae253e013da716ea870347304402203b1500cf7ffe0a4e574dc822f01cf65b69912a5412c496c709dd449ae1f2b36202204193476d175d93a8b90fec1746f63dd0c104a8552f567a5bc50f17125607a81d01004d63210226ac4d994613cffbc5db677ca43ba36e4411b3f35a4c9a81333c32a42665c08067029000b2752103355dd461d0517fec30ab4785f127f77830fec8d34aa0028922f6de28af8859e568ac00000000

2018-05-26 11:43:51,393 ERROR fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - peer sent error: ascii='lightning_channeld: received ERROR channel e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb: forced local commit: reason' bin=6c696768746e696e675f6368616e6e656c643a207265636569766564204552524f52206368616e6e656c20653330333362343632366330613138633836666131656664373636313136633836653639336239393637353034373531363864376231646364393937333166623a20666f72636564206c6f63616c20636f6d6d69743a20726561736f6e

2018-05-26 11:49:28,124 WARN  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - they published their current commit in txid=593af684ec36e529fa5d98199108245681056ee9dba138602309164c31f6a383
2018-05-26 11:49:28,238 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - tx generation success: desc=claim-p2wpkh-output txid=5797030740f588c35ff0a4c9001b64f751aaf79af664dc0d599b47d3a16aadda amount=129159 tx=0200000000010183a3f6314c1609236038a1dbe96e05815624089119985dfa29e536ec84f63a590000000000000000000187f801000000000017a9140c268e1cfd549df4c269958fae253e013da716ea87024730440220026449e89ce40f801b088501c7835877d554184e6f7f929ac51984992e035c69022014ef14900c7aacdfe9eafd435e48d53ba59f92045b47b3c297bed241f0168668012102dc168c08afd6f86706f5ef13d63dc3f5953e2fbce40a0577c328e56ed6e0c1a800000000

2018-05-26 12:01:09,703 WARN  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - unhandled event WatchEventConfirmed(BITCOIN_FUNDING_DEPTHOK,524516,283) in state CLOSING

2018-05-26 12:11:35,109 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb - txid=593af684ec36e529fa5d98199108245681056ee9dba138602309164c31f6a383 has reached mindepth, updating closing state

2018-05-27 17:58:38,924 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a 0000000000000000000000000000000000000000000000000000000000000000 - restoring channel channelId=e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fb
2018-05-27 17:58:38,928 INFO  fr.acinq.eclair.gui.GUIUpdater akka://default/user/$a/gui-updater  - new channel: Actor[akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a#-1056071713]
2018-05-27 17:58:38,929 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a 0000000000000000000000000000000000000000000000000000000000000000 - funding tx has already been spent and spending tx reached mindepth, no need to put back the watch-spent

2018-05-27 17:58:38,971 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - publishing tx (isRetry=false): txid=3e0e94ed8190cfccde3024492bf79675cfec09e4489ee4c88a1f96baffc781d6 tx=02000000000101e3033b4626c0a18c86fa1efd766116c86e693b996750475168d7b1dcd99731fa01000000009292228001f4f801000000000022002085df57d3b93239139e536ee545714ed96ebca24e7fe13fd5db3a37acff7e8984040048304502210099d9bb22d42fd812c7434b8912ff901d52666a560d96a5ff23bc05887f2b8d2f02200be36e4a9c40e91ef29bd6a3d80e34fe90e6a6bb29d7f1fd35b53ca01ad00ce90147304402202cb0c4ce8d685e35f194752321dc9d44f2d3909b6929f0e3304fcb87a1e1144002200d8114d2c34a013bebffe2da371dab5ee052ae57c9e74332d22ac4a0322de6300147522102b8ccbaf222c8b57b47648dc3740fe9766d2b01cd5ff22108a7615c299d4036762103dcb6fc88ded460672ee010b40fb3932a0bee3611caa1c09cdc9ef4cacff1bf8052ae1e39e020
2018-05-27 17:58:38,983 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - txid=6a04077bc3027e16319ef324521652789a4523e4c27d471ac9cb181c12e11285 has a relative timeout of 144 blocks, watching parenttxid=3e0e94ed8190cfccde3024492bf79675cfec09e4489ee4c88a1f96baffc781d6 tx=02000000000101d681c7ffba961f8ac8e49e48e409eccf7596f72b492430decccf9081ed940e3e000000000090000000017cf801000000000017a9140c268e1cfd549df4c269958fae253e013da716ea870347304402203b1500cf7ffe0a4e574dc822f01cf65b69912a5412c496c709dd449ae1f2b36202204193476d175d93a8b90fec1746f63dd0c104a8552f567a5bc50f17125607a81d01004d63210226ac4d994613cffbc5db677ca43ba36e4411b3f35a4c9a81333c32a42665c08067029000b2752103355dd461d0517fec30ab4785f127f77830fec8d34aa0028922f6de28af8859e568ac00000000
2018-05-27 17:58:38,987 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$i/switchboard/peer-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432/$a 0000000000000000000000000000000000000000000000000000000000000000 - no need to watch txid=593af684ec36e529fa5d98199108245681056ee9dba138602309164c31f6a383, it has already been confirmed
2018-05-27 17:58:38,998 INFO  f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - publishing tx (isRetry=false): txid=5797030740f588c35ff0a4c9001b64f751aaf79af664dc0d599b47d3a16aadda tx=0200000000010183a3f6314c1609236038a1dbe96e05815624089119985dfa29e536ec84f63a590000000000000000000187f801000000000017a9140c268e1cfd549df4c269958fae253e013da716ea87024730440220026449e89ce40f801b088501c7835877d554184e6f7f929ac51984992e035c69022014ef14900c7aacdfe9eafd435e48d53ba59f92045b47b3c297bed241f0168668012102dc168c08afd6f86706f5ef13d63dc3f5953e2fbce40a0577c328e56ed6e0c1a800000000
2018-05-27 17:58:39,526 INFO  fr.acinq.eclair.Setup   - initial wallet address=3PFnojw3incXkQhcARt8D9Z4VyvEiHm18D
2018-05-27 17:58:39,762 ERROR f.a.e.blockchain.bitcoind.ZmqWatcher akka://default/user/$c/watcher  - cannot publish tx: reason=66: min relay fee not met (code: -26) txid=5797030740f588c35ff0a4c9001b64f751aaf79af664dc0d599b47d3a16aadda tx=0200000000010183a3f6314c1609236038a1dbe96e05815624089119985dfa29e536ec84f63a590000000000000000000187f801000000000017a9140c268e1cfd549df4c269958fae253e013da716ea87024730440220026449e89ce40f801b088501c7835877d554184e6f7f929ac51984992e035c69022014ef14900c7aacdfe9eafd435e48d53ba59f92045b47b3c297bed241f0168668012102dc168c08afd6f86706f5ef13d63dc3f5953e2fbce40a0577c328e56ed6e0c1a800000000

**Comment by sstone** [comment] 2018-05-28 08:47
Duplicate of https://github.com/ACINQ/eclair/issues/602, please monitor progress there (there is a solution to recompute a valid transaction)

**Closed as completed by sstone** 2018-05-28 08:47 UTC
