### ISSUE TITLE
Use all available funds to create a channel

### ISSUE THREAD

**Issue by Kixunil** [ACINQ/eclair-mobile#124] opened 2018-09-28 20:41 UTC
It'd be great, if there was a button/checkbox when creating a channel that would allow one to use all available  funds to open a channel in order to avoid leaving dust in the wallet.

**Comment by irekzielinski** [comment] 2018-10-21 21:09
It's a duplicate of #53
I fully agree that this would be VERY helpful.

**Closed as completed** 2018-10-26 13:27 UTC
Labels: feature request
