### ISSUE TITLE
Payment failed with "Channel xxx is currently unavailable"

### ISSUE THREAD

**Issue by mstrokin** [ACINQ/eclair-mobile#84] opened 2018-06-11 02:13 UTC
Trying to make a LN payment to node where recipient node and eclair wallet are directly connected to ACINQ. Every payment fails with same 10 failed channels (7fdb70004f40000 , 7f9450005520000 , etc).
It seems some of the channels are stuck and wallet keeps trying to use them without realizing that these channels are not usable?

Node URI:
032b31feacb6d645c9a83a015d2b52d549205ef515ddea9f0a6b8a4a657eefec3a@94.130.239.161:9735

**Comment by mstrokin** [comment] 2018-06-11 02:38
It seems it tries to use channels which were closed before*

**Comment by sstone** [comment] 2018-06-12 16:01
This should work (I've tested with my own eclair wallet connected to endurance, and another node also connected to endurance), but only if you have enough money on the second channel: what you have is

```
eclair [local balance] ----> [remote balance] endurance [remote balance] <----------- [ local balance] your node
```
When you create these channels, funds are on the outside (your node and your mobile wallet). To be able to pay your node you need some funds on the "remote" side of your seconds channel. Just make a few payments from your node to anyone through endurance, and then you will be able to receive funds.

**Comment by mstrokin** [comment] 2018-06-13 23:14
In other words, if ACINQ opens and funds a channel to our node, this issue wouldn't exist? 

If so, does that mean that as a vendor we have to: 
1) create some channels
2) pay through these channels to someone else (and I guess ACINQ has to be the creator of ACINQ->someone channel or have some funds in that channel otherwise) so that our 'remote' end gets enough funds available to be sent back to us when users pay to us through that channel?

**Comment by mmvphil** [comment] 2018-06-14 06:28
Yep I got same problem and IT BLOWS BIG time!  Routing and funded reliability are stopping me from writing my own apps. Not eclair's fault but I think a lot of dweebs running nodes part time and unfunded.. makes matters worse. Whats the proper way to solve this as I want to write apps for my node (send/recieve) and was hoping that connecting to eclair's channel could solve that?  Whats the node to connect to?

**Comment by sstone** [comment] 2018-06-18 10:07
Yes, one of the limitations of LN currently is that channels are not balanced when they are created, and the fact that payment flows are not symmetrical (i.e a lot of payments move in the "same direction") does not help, but it has already improved a lot. 
Reliability of LN nodes on mainnet has also improved a lot on mainnet (on testnet it's a bit wild, but it's good for testing :)), and payment capacity is getting better as well (as it becomes more reliable people will start opening larger channels, at the beginning people were rightfully cautious).

So if you want to receive funds, you need:
- to have move some funds to the other side of channels that you created (it will happen as soon as you start using them, no matter who you're paying)
- open channels using push_msat so there are funds on your peer's end from the start. it is not used a lot yet because it requires some external setup (for example B sends an onchain tx to A, which opens a channel to B with a matching  push_msat, or B is a service that "owns" some of A's fund and can be asked to open a channel to A with some value in push_msat)

There is ongoing work which should improve this a lot, for example dual funding, where each node could add funds to the funding tx and start with a channel that is fairly well balanced (there is a PR that was too late for the current specs), or re-anchoring (i.e. replacing a channel's funding tx)

**Comment by sstone** [comment] 2018-06-21 08:08
I'm closing this because it is not a bug in our wallet but rather a limitation of the current specs (to receive money you need funds on the "remote" side of a channel, and when you open them all the money is on your side).

**Closed as completed by sstone** 2018-06-21 08:08 UTC
