### ISSUE TITLE
Release this app via F-Droid

### ISSUE THREAD

**Issue by blacktemplar** [ACINQ/eclair-mobile#221] opened 2019-10-11 06:06 UTC
As an android user without GApps I would really like to see this app in the F-Droid app store. At the moment I have to install the apk myself and don't get automatic updates (which may be VERY important at this stage of the development).

**Comment by araspitzu** [comment] 2019-10-11 07:35
Duplicate of https://github.com/ACINQ/eclair-mobile/issues/221

**Closed as completed by araspitzu** 2019-10-11 07:35 UTC
Labels: duplicate

**Comment by blacktemplar** [comment] 2019-10-12 05:31
I don't understand, why was this closed as a duplicate of itself ^^?

**Comment by t-bast** [comment] 2019-10-12 12:28
Damn, we hoped you wouldn't notice xD
We meant #214  ;)
