### ISSUE TITLE
Channel with Bitrefill goes offline and online all the time.

### ISSUE THREAD

**Issue by bitcoinuser** [ACINQ/eclair-mobile#82] opened 2018-06-03 16:42 UTC
Channel with Bitrefill goes offline and online all the time.

See the video uploaded.
[2018_06_03_13_29_07.mp4.zip](https://github.com/ACINQ/eclair-wallet/files/2066149/2018_06_03_13_29_07.mp4.zip)

**Comment by sstone** [comment] 2018-06-03 20:24
On your video it's offline all the time ? 
I have a channel with bitrefill, it's online and has been steady for some time.

**Comment by bitcoinuser** [comment] 2018-06-03 22:25
> On your video it's offline all the time ?

It's not online all time. In seconds change from offline to online then offline again....

**Comment by juscamarena** [comment] 2018-06-04 04:34
I'm seeing this two on eclair on android with my phone, flickering online and offline.

**Comment by sstone** [comment] 2018-06-05 11:46
Which version of `lnd` are you using ? 
EDIT: is there anything relevant in your lnd logs ?

**Comment by bitcoinuser** [comment] 2018-06-05 15:42
Now everything is working ok.

**Comment by bitcoinuser** [comment] 2018-06-05 17:40
Reproducing again.

**Comment by vegardengen** [comment] 2018-06-05 18:39
THere's a problem around the data loss protection stuff. I haven't research all this fully, yet, but according to my understanding, here's what happens:

- LND signals for data loss protection.
- Eclair thinks "cool!" and goes on to use some compression stuff that is not in the spec yet...
- LND says "wtf is this!" and disconnects.

**Comment by sstone** [comment] 2018-06-05 20:53
Yes, we're aware of it. What happened is that lnd on master (very recently, after their last release) added an experimental LN feature (fast routing table sync) and they have it activated by default. Their implementation is not fully compatible with ours (and with the specs imho but this feature is in a PR that has not been merged so implementation details are still being discussed).
It is very likely that most "major" lnd node operators (including bitrefill) that are willing to run lnd master on mainnet will deactivate this experimental feature. I've also added a change that will fix this, but it will take a few days before it's deployed on our mobile app.

**Comment by bitcoinuser** [comment] 2018-06-06 15:38
Now it's all time online, but payments pending. https://mainnet.yalls.org always worked but now everytime I try goes pending. 

![photo4954486926648387536](https://user-images.githubusercontent.com/1178856/41049126-8f19b54a-6986-11e8-9659-29deabb7acd7.jpg)

**Comment by juscamarena** [comment] 2018-06-06 18:30
Can you try again? Disabled some stuff on my end manually.

**Comment by bitcoinuser** [comment] 2018-06-06 20:11
> Can you try again? Disabled some stuff on my end manually.

Same problem.

**Comment by jaycrypt0** [comment] 2018-06-07 00:17
I am having issues paying @bitrefill still using ACINQ node.

**Comment by irekzielinski** [comment] 2018-06-08 19:31
Tried to open a channel with bitrefill today, with the latest version of Eclair wallet from Play store.
Was togging between offline and waiting for funding. Soon after it went into uncooperative close.

[Movie of the toggling](https://www.dropbox.com/s/2sbgan8s6gpgo9t/20180608_202020.mp4?dl=0)
[Final state screen-shot](https://www.dropbox.com/s/qtvktpyybqx950e/ln-closethumbnail.jpeg?dl=0)

**Comment by sstone** [comment] 2018-06-12 15:10
It turns out that there are 2 different, unrelated issues here:

- an incompatibility between lnd's and eclair's implementation of a new LN feature (see https://github.com/lightningnetwork/lightning-rfc/pull/392) that is still being specified. It was activated recently on lnd (but after their latest release), but I think most lnd operators have deactivated it now. It's very easy to spot in lnd's logs (will complain about invalid encoding type 1 which is the zlib format). a new mobile app will be released soon with a change that will make it work with lnd.  This feature will be finalized soon and all implementations will converge.
- a more serious issue (because it also affects server nodes, not just mobile apps), where lnd still thinks it has a connection and will refuse new ones, when it fact the old connection is inactive or dead. See https://github.com/lightningnetwork/lnd/issues/1337 for more details. This is caused by a change that was also added after their latest release, so if you're running a released version of lnd you should be fine.

**Comment by irekzielinski** [comment] 2018-06-12 19:23
Appreciated @sstone :-)

**Comment by sstone** [comment] 2018-06-14 09:00
We've released version 0.3.4 of eclair wallet for testnet and mainnet, which includes a change to support peers who activated [channel range queries](https://github.com/lightningnetwork/lightning-rfc/pull/392) but don't implement zlib compression (i.e lnd on their latest commits). It will fix some of the issues that people experience with lnd nodes running on master.

It will not, however, fix the connection problems that people are experiencing with some lnd nodes (not just witch eclair, it even happens when you're using lnd to connect to lnd, see https://github.com/lightningnetwork/lnd/issues/1337): the node you're trying to connect to wrongly thinks you're already connected and won't let you, there is nothing you can do. So if you're running lnd on master make sure you're up to date and include the fix for 1337.

**Comment by sstone** [comment] 2018-06-21 08:13
Closing because lnd's reconnection issue has been fixed and it seems that most "large" lnd nodes have been upgraded.

**Closed as completed by sstone** 2018-06-21 08:13 UTC
