### ISSUE TITLE
Channel closing (uncooperative) - no progress in status even after 144 blocks

### ISSUE THREAD

**Issue by griswaalt** [ACINQ/eclair-mobile#27] opened 2018-04-08 07:52 UTC
So I set up a channel with the SLEEPYARK node to buy some blockstream stickers. However, since my funding amount was a bit less, I couldn't make a purchase tx so I decided to close the channel. On clicking close, the status changed to closing (uncooperative) and there has been no progress since then. I closed the channel over 2 days back so it is well past 144 blocks. However, there is no on chain tx to return my funds and I see the status as closing (uncooperative). Any ideas what could be the issue?
![screenshot_20180408-094843](https://user-images.githubusercontent.com/1517635/38464708-88cb9688-3b12-11e8-95b7-a076210220b5.png)

**Comment by ghost** [comment] 2018-04-08 08:25
Identical to https://github.com/ACINQ/eclair-wallet/issues/17
Unfortunately I was not lucky to get logs and figure out the exact cause, but it's a good thing it can be reproduced easily so devs will be able to fix

**Comment by pm47** [comment] 2018-04-08 09:47
@griswaalt @gustavonalle Any of you has a rooted phone? Being able to access app data would facilitate debugging a lot

**Comment by griswaalt** [comment] 2018-04-08 10:25
@pm47 I am running this on stock, unrooted Android.

**Comment by ghost** [comment] 2018-04-08 10:28
@pm47 If you run the app in the android studio using the emulator in debug mode, put 2 mBTC, wait for confirmation, open a channel to a node you control, kill that node, forcefully close the channel in the emulator, you'll probably be able to reproduce the issue, since pretty much everyone is seeing it.

Now, since you lost the password to update the app on google play (https://twitter.com/acinq_co/status/982749523104673792), the question is if it's possible to manually create a tx to redeem the funds stuck in the wallet or create a script/app to do so...

**Comment by pm47** [comment] 2018-04-08 10:43
Yes we are doing that, but the more information the better

> the question is if it's possible to manually create a tx to redeem the funds stuck in the wallet or create a script/app to fix the issue...

Not without the app data, because there is per-channel random data that is generated by each peer for each channel

**Comment by ghost** [comment] 2018-04-08 11:00
>  Not without the app data

You mean not without rooting the phone and reading the SQL DB?

**Comment by pm47** [comment] 2018-04-08 11:07
>> Not without the app data

>You mean not without rooting the phone and reading the SQL DB?

Yes

**Comment by ghost** [comment] 2018-04-08 11:30
Hmmm...that's bad :(

What if I build the app directly from (bug fixed) sources and manually install it on the phone?

**Comment by pm47** [comment] 2018-04-08 11:50
> What if I build the app directly from (bug fixed) sources and manually install it on the phone?

If you do that, signature will be different and android will reinstall the app, deleting the data in the process :-/

**Comment by ghost** [comment] 2018-04-08 12:11
I can see you also have ```android:allowBackup="false"``` in the Android manifest, which would prevent obtaining the data via a backup with the user permission 😭

**Comment by pm47** [comment] 2018-04-08 12:15
Yes, this is by designed. The app data is completely locked from the inside

**Comment by dognip** [comment] 2018-04-08 12:22
So it sounds like either we root our phones or we lose the funds? Is that correct?

**Comment by pm47** [comment] 2018-04-08 12:25
We don't know yet, I haven't even been able to reproduce the issue. As soon as we understand exactly what the problem is, we'll be able to tell

**Comment by gustavonalle** [comment] 2018-04-08 12:29
Looks so, unless the devs ask Google for another key to be able to update the app:

```If you're enrolled in Google Play App Signing, you can reset your upload key if:

You lost your private key, or
Your private key has been compromised
Note: Resetting your upload key will not affect the app signing key that Google Play uses to re-sign APKs before delivering to users.
```

I have a strong feeling that they are not "enrolled in Google Play App Signing" though :smile:

**Comment by pm47** [comment] 2018-04-08 19:44
This is a duplicate of #17, please see updates there.

**Closed as completed by pm47** 2018-04-08 19:44 UTC
Labels: duplicate
