### ISSUE TITLE
Channel closed and funds not refunded.

### ISSUE THREAD

**Issue by ttajaf68** [ACINQ/eclair-mobile#16] opened 2018-04-05 22:24 UTC
channel closed uncooperatively.  App became inaccessible when attempting to check refund next day. App was uninstalled, reinstalled and recovered and funds still missing.

**Comment by sstone** [comment] 2018-04-06 15:37
Did you initiate the closing of the channel ? What do you mean by "inaccessible" (what happened when you restarted the app) ?

**Comment by ttajaf68** [comment] 2018-04-06 21:48
I iniated the closing. The first couple of times I tried to restart the app it said something about 'startup taking too long so' cancelling/aborting. After that it just showed a pop up saying unable to start. It was the apk off here verified installed on a samsung gt-i9195 (android 7.1.2 / lineage 14.1.20170825-NIGHTLY)

**Comment by ttajaf68** [comment] 2018-04-06 21:50
i re-installed from play store and entered my seed to recover wallet. No app start up problems since but no funds returned from channel.

**Comment by mautematico** [comment] 2018-04-06 23:49
channel funds are not backed up by seed words; it is stated on the screen that gives you seed words.

For me it seems that you did not complete channel clossing. 

I think your funds are lost forever, unless... If I understand correctly, if/when your counterparty closses the channel (after so long time of being unable to reach you), your funds should re-appear.

**Comment by ttajaf68** [comment] 2018-04-07 05:19
i am talking about 2 separate things. first the channel was closed. Then the next day I could not access the app so I had to reinstall it and use my seed to restore the wallet. I reinstalled the app and used my seed about 24 hours after the channel was closed so I would have expected the funds to have gone back by then.

**Comment by mautematico** [comment] 2018-04-07 15:35
Then you're confusing how the protocol works.

When you (uncoop) close a channel, you must wait for it to complete close operation.
(uncoop) Closing transaction can't be confirmed before N-height of blocks, and AFAIK eclair won't relay it to the network until said N is reached.

So basically your channel was not closed, but in a state like _waiting for (uncoop) close_, I think.

**Comment by ttajaf68** [comment] 2018-04-07 18:41
Sorry. If I could have accessed the app normally the next day when I attempted to then eclair would have relayed it and I would have had my funds returned ?

**Comment by pm47** [comment] 2018-04-08 19:46
@ttajaf68 normally yes, however we have a pending bug (#17) that currently prevents it.

I'm closing this, because you have deleted your data and there is nothing we can do anymore now.

**Closed as completed by pm47** 2018-04-08 19:46 UTC

**Comment by mautematico** [comment] 2018-04-08 23:22
@pm47 please could you confirm or refuse:

As per LN protocol, if remote node (uncoop) closes same channel after some time of it being disconnected, should OP recover its funds?

@ttajaf68 there is no need to be sorry, we're here trying our best to help you, no strings attached :)
